export const programmingLanguages = [
  { name: "JavaScript", color: "#f1e05a" },
  { name: "Python", color: "#3572A5" },
  { name: "Java", color: "#b07219" },
  { name: "C++", color: "#f34b7d" },
  { name: "C#", color: "#178600" },
  { name: "Ruby", color: "#701516" },
  { name: "Go", color: "#00ADD8" },
  { name: "TypeScript", color: "#2b7489" },
  { name: "Swift", color: "#ffac45" },
  { name: "Rust", color: "#dea584" },
  { name: "PHP", color: "#4F5D95" },
  { name: "C", color: "#555555" },
  { name: "Objective-C", color: "#438eff" },
  { name: "Shell", color: "#89e051" },
  { name: "Scala", color: "#c22d40" },
  { name: "Kotlin", color: "#f18e33" },
  { name: "R", color: "#198ce7" },
  { name: "Lua", color: "#000080" },
  { name: "Perl", color: "#0298c3" },
  { name: "Haskell", color: "#5e5086" },
  { name: "Dart", color: "#00B4AB" },
  { name: "Julia", color: "#a270ba" },
  { name: "Elixir", color: "#6e4a7e" },
  { name: "Clojure", color: "#db5855" },
  { name: "Groovy", color: "#e69f56" },
  { name: "TeX", color: "#3D6117" },
  { name: "Vim script", color: "#199f4b" },
  { name: "Assembly", color: "#6E4C13" },
  { name: "PowerShell", color: "#012456" },
  { name: "Roff", color: "#ecdebe" },
  { name: "Erlang", color: "#B83998" },
  { name: "CoffeeScript", color: "#244776" },
  { name: "F#", color: "#b845fc" },
  { name: "Haxe", color: "#df7900" },
  { name: "ClojureScript", color: "#db5855" },
  { name: "Emacs Lisp", color: "#c065db" },
  { name: "Arduino", color: "#bd79d1" },
  { name: "Crystal", color: "#000100" },
  { name: "Verilog", color: "#b2b7f8" },
  { name: "VHDL", color: "#adb2cb" },
  { name: "Vala", color: "#fbe5cd" },
  { name: "Common Lisp", color: "#3fb68b" },
  { name: "D", color: "#ba595e" },
  { name: "DM", color: "#447265" },
  { name: "Nim", color: "#ffc200" },
  { name: "Objective-C++", color: "#6866fb" },
  { name: "Pascal", color: "#E3F171" },
  { name: "PureScript", color: "#1D222D" },
  { name: "ABAP", color: "#E8274B" },
  { name: "ActionScript", color: "#882B0F" },
  { name: "HTML", color: "#e34c26" },
  { name: "CSS", color: "#563d7c" },
  // Add more languages as needed
];
